FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential python-is-python3 cmake pkg-config libfmt-dev libspdlog-dev nlohmann-json3-dev \
    libgrpc++-dev protobuf-compiler-grpc libssl-dev

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
